package com.hrms.modules.devTools.autoGeneratedCode;

import lombok.Data;

@Data
public class AutoGenModule {
    private String sourceUrl;
    private String packageName;
    private String domainName;
}
