package com.hrms.modules.devTools.autoGeneratedCode;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.web.bind.annotation.*;


import java.io.IOException;

@RestController
@RequestMapping("/dev")
@CrossOrigin("*")

public class DevController {
    @Autowired
    private DevService devService;


    @Value("classpath:")
    private Resource[] resources;

    @PostMapping("/create")
    public void create(@RequestBody AutoGenModule autoGenModule) throws IOException {
        this.devService.create(autoGenModule);
    }

    @GetMapping("/")
    public String home() throws IOException {
        for (final Resource res : resources) {
            DevController devController = new DevController();
            System.out.println("OK=========="+devController.getClass());
            Package devC= devController.getClass().getPackage();
            System.out.println("Package"+devC);
//            ApplicationHome home = new ApplicationHome(HRMSApplication.class);
//            home.getDir();    // returns the folder where the jar is. This is what I wanted.
//            home.getSource();
//            System.out.println(home.getDir()+"------"+home.getSource());
            System.out.println( getClass().getResource("").toString());
        }
        return "blog/a";
    }
}
